#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cachet"
name = "Cachet"
description.en = "Status page to inform users about the state of online services"
description.fr = "Page de statut pour informer les utilisateur·ice·s de l'état de services en ligne"

version = "2026.08.17~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "BSD-3-Clause"
website = "https://cachethq.io"
demo = "https://demo.cachethq.io"
admindoc = "https://docs.cachethq.io"
code = "https://github.com/CachetHQ/Cachet"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
	[install.domain]
	type = "domain"

	[install.init_main_permission]
	type = "group"
	default = "visitors"

	[install.language]
	ask.en = "Choose the application language"
	ask.fr = "Choisissez la langue de l'application"
	type = "select"
	choices = ["fr", "en"]
	default = "en"

	[install.admin]
	type = "user"

	[install.password]
	type = "password"

[resources]
	[resources.sources.main]
	url = "https://github.com/CachetHQ/Cachet/archive/161262d137f1c64f84f26821ea7fc9e9761cf00a.tar.gz"
	sha256 = "620c865b33ff8279af6623081e489f30a92997f6459fe102912fad8bab1670a7"
	autoupdate.strategy = "latest_github_commit"

	[resources.system_user]

	[resources.install_dir]
	group = "www-data:r-x"

	[resources.permissions]
	main.url = "/"

	[resources.apt]
	packages = [
		"mariadb-server",
		"php8.4",
		"php8.4-gd",
		"php8.4-mbstring",
		"php8.4-xml",
		"php8.4-mysql",
		"php8.4-sqlite3",
		"php8.4-intl",
		"php8.4-zip",
		"php8.4-curl"
	]

	[resources.database]
	type = "mysql"

	[resources.composer]
	version = "2.8.5"