packaging_format = 2

id = "cachet"
name = "Cachet"
description.en = "Open source status page system"
description.fr = "Système de page de statut open source"

version = "2023.08.11~ynh6"

maintainers = ["JimboJoe"]

[upstream]
license = "BSD-3-Clause"
website = "https://cachethq.io"
demo = "https://demo.cachethq.io"
admindoc = "https://docs.cachethq.io"
code = "https://github.com/CachetHQ/Cachet"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = true

[resources]
        [resources.sources.main]
        url = "https://github.com/CachetHQ/Cachet/archive/a2176c8c56d7910b916113741dbec5577d9e5589.tar.gz"
        sha256 = "3ea5e67ab1d4ada4c065901cfb2bf5dfdd8bbb40b29b331967f09e176c8799b4"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php7.4-gd php7.4-mbstring php7.4-xml php7.4-mysql php7.4-sqlite3"

    [resources.database]
    type = "mysql"
