#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cachet"
name = "Cachet"
description.en = "Open source status page system"
description.fr = "Système de page de statut open source"

version = "2024.12.23~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "BSD-3-Clause"
website = "https://cachethq.io"
demo = "https://demo.cachethq.io"
admindoc = "https://docs.cachethq.io"
code = "https://github.com/CachetHQ/Cachet"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = true

[resources]
    [resources.sources.main]
    url = "https://github.com/CachetHQ/Cachet/archive/9cf1ff5f17eb0f7973295749c2bd6d53b6d7ddde.tar.gz"
    sha256 = "884ac0ae23a2d5bd91a5febe39761cb6acc2d9a6edbbed5d3160f64bffc76576"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.3",
        "php8.3-gd",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-mysql"
    ]

    [resources.database]
    type = "mysql"
