#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cachet"
name = "Cachet"
description.en = "Open source status page system"
description.fr = "Système de page de statut open source"

version = "2024.03.11~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "BSD-3-Clause"
website = "https://cachethq.io"
demo = "https://demo.cachethq.io"
admindoc = "https://docs.cachethq.io"
code = "https://github.com/CachetHQ/Cachet"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = true

[resources]
    [resources.sources.main]
    url = "https://github.com/CachetHQ/Cachet/archive/3e97a874fad1c2a0243b247d2c4e89eb81bac477.tar.gz"
    sha256 = "707045be6e638f120651e4e48e84614599683554fd45f1bbdd90b407d125d6e9"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php7.4",
        "php7.4-gd",
        "php7.4-mbstring",
        "php7.4-xml",
        "php7.4-mysql",
        "php7.4-sqlite3"
    ]

    [resources.database]
    type = "mysql"
