#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cachet"
name = "Cachet"
description.en = "Open source status page system"
description.fr = "Système de page de statut open source"

version = "2.4.1~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "BSD-3-Clause"
website = "https://cachethq.io"
demo = "https://demo.cachethq.io"
admindoc = "https://docs.cachethq.io"
code = "https://github.com/CachetHQ/Cachet"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = true

[resources]
    [resources.sources.main]
    url = "https://github.com/cachethq/cachet/archive/refs/tags/v2.4.1.tar.gz"
    sha256 = "9dbe47e83de1baedf5e960611211056541ed85bbad869184ca8c1cf5ad5c6244"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.3",
        "php8.3-gd",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-mysql",
        "php8.3-sqlite3"
    ]

    [resources.database]
    type = "mysql"
