#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cachet"
name = "Cachet"
description.en = "Status page to inform users about the state of online services"
description.fr = "Page de statut pour informer les utilisateur·ice·s de l'état de services en ligne"

version = "2026.07.08~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "BSD-3-Clause"
website = "https://cachethq.io"
demo = "https://demo.cachethq.io"
admindoc = "https://docs.cachethq.io"
code = "https://github.com/CachetHQ/Cachet"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    optional = true

[resources]
    [resources.sources.main]
    url = "https://github.com/CachetHQ/Cachet/archive/db6854451022edeb2e493462364173b1acef73bf.tar.gz"
    sha256 = "c3bbb9bb418e53e6856faca34b7f6809936ef1431d73ce8b88a8c38ca523ed1c"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "redis-server",
        "mariadb-server",
        "php8.4-fpm",
        "php8.4-gd",
        "php8.4-mbstring",
        "php8.4-xml",
        "php8.4-mysql",
        "php8.4-sqlite3",
        "php8.4-intl",
        "php8.4-zip",
    ]

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.9.2"
