test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.6fcddf81286fb845735978ed832c9273c3b783ce.name = "Upgrade from 2.4.0~ynh4"
    test_upgrade_from.2279c40608c21d087d91d1cdb62d91693bd7d703.name = "Upgrade from 2024.06.14~ynh1"