#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.6b05143cad46a3114b25d5211f05250792c60186.name = "Upgrade from 2.4.1~ynh2"
    test_upgrade_from.07ba19dd00c3144adfdb4848ba93cd72abf67381.name = "Upgrade from 2026.07.25~ynh1"
