#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.6fcddf81286fb845735978ed832c9273c3b783ce.name = "Upgrade from 2.4.0~ynh4"
    test_upgrade_from.dceef0ff276a2f1b62226e8c41a39d212852db6c.name = "Upgrade from 2.4.1~ynh1"