#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=2

ynh_change_url_nginx_config

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

ynh_backup_if_checksum_is_different --file="$install_dir/.env"

# Replace domain in Cachet configuration files
ynh_replace_string --match_string="$old_domain" --replace_string="$new_domain" --target_file="$install_dir/.env"

ynh_store_file_checksum --file="$install_dir/.env"

# Replace domain in Cachet database settings
ynh_mysql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name"  <<< "UPDATE settings SET value = 'https://$new_domain' WHERE name = 'app_domain'"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
