#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_backup_if_checksum_is_different "$install_dir/.env"
ynh_backup_if_checksum_is_different "$install_dir/bootstrap/cachet/production.php"

# Replace domain in Cachet configuration files
ynh_replace --match="$old_domain" --replace="$new_domain" --file="$install_dir/.env"
ynh_replace --match="$old_domain" --replace="$new_domain" --file="$install_dir/bootstrap/cachet/production.php"

ynh_store_file_checksum "$install_dir/.env"
ynh_store_file_checksum "$install_dir/bootstrap/cachet/production.php"

# Replace domain in Cachet database settings
ynh_mysql_db_shell <<< "UPDATE settings SET value = 'https://$new_domain' WHERE name = 'app_domain'"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
