#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SET MAINTENANCE MODE ON
#=================================================

# We need to have the required version of PHP, hence PHP-FPM block is executed beforehand
exec_artisan "down"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env bootstrap/cachet/production.php"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
chown -R $app: "${install_dir}/.env" "${install_dir}/storage/" "${install_dir}/bootstrap/"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# INSTALL AND INITIALIZE COMPOSER
#=================================================
ynh_script_progression "Upgrading Cachet configuration and dependencies..."

ynh_composer_install
ynh_composer_exec install --no-dev  --optimize-autoloader

#=================================================
# UPDATE CACHET CONFIGURATION
#=================================================

exec_artisan "app:update"
ynh_safe_rm bootstrap/cache/*

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
chown -R $app: "${install_dir}/.env" "${install_dir}/storage/" "${install_dir}/bootstrap/"

#=================================================
# SET MAINTENANCE MODE OFF
#=================================================

exec_artisan "up"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
